version: '3.9'
services:
  grpc-server:
    build:
      dockerfile: ./docker/grpc/Dockerfile
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
  grpc-client:
    build:
      dockerfile: ./docker/grpc/Dockerfile
      context: ./
    command: echo "do nothing"
    volumes:
      - ./:/app                
  rdb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grpc-up-and-running
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
